"""initial schema: season, team, venue, match, ingestion_log

Revision ID: 1442bd5671d4
Revises: 
Create Date: 2026-08-11 18:02:40.045453

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1442bd5671d4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_log",
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("run_started_at", sa.DateTime(), nullable=False),
        sa.Column("run_finished_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("records_fetched", sa.Integer(), nullable=True),
        sa.Column("records_loaded", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=512), nullable=True),
        sa.CheckConstraint(
            "status IN ('success', 'partial', 'failed')",
            name="ck_ingestion_log_status_enum",
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_table(
        "season",
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=16), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("season_id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "venue",
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("venue_id"),
    )
    op.create_table(
        "team",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("short_name", sa.String(length=32), nullable=True),
        sa.Column("canonical_key", sa.String(length=64), nullable=False),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("venue_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venue.venue_id"],
        ),
        sa.PrimaryKeyConstraint("team_id"),
        sa.UniqueConstraint("canonical_key"),
    )
    op.create_table(
        "match",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("match_date", sa.Date(), nullable=False),
        sa.Column("matchweek", sa.Integer(), nullable=True),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=True),
        sa.Column("home_goals", sa.Integer(), nullable=True),
        sa.Column("away_goals", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'played', 'postponed', 'abandoned')",
            name="ck_match_status_enum",
        ),
        sa.CheckConstraint(
            "home_team_id <> away_team_id", name="ck_match_distinct_teams"
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["team.team_id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["team.team_id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.season_id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venue.venue_id"],
        ),
        sa.PrimaryKeyConstraint("match_id"),
        sa.UniqueConstraint(
            "season_id",
            "home_team_id",
            "away_team_id",
            "match_date",
            name="uq_match_natural_key",
        ),
    )
    op.create_index("ix_match_away_team", "match", ["away_team_id"], unique=False)
    op.create_index("ix_match_date", "match", ["match_date"], unique=False)
    op.create_index("ix_match_home_team", "match", ["home_team_id"], unique=False)
    op.create_index(
        "ix_match_season_matchweek", "match", ["season_id", "matchweek"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_match_season_matchweek", table_name="match")
    op.drop_index("ix_match_home_team", table_name="match")
    op.drop_index("ix_match_date", table_name="match")
    op.drop_index("ix_match_away_team", table_name="match")
    op.drop_table("match")
    op.drop_table("team")
    op.drop_table("venue")
    op.drop_table("season")
    op.drop_table("ingestion_log")
    # ### end Alembic commands ###
